[package]
name = "pygmy-backend"
version = "0.1.0"
authors = ["Hao Shi <shisoftgenius@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "2.0"
actix-rt = "1.0"
diesel = { version = "1.0.0", features = ["sqlite"] }
dotenv = "0.9.0"
lazy_static = "1.4.0"
serde = { version = "1.0", features = ["derive"] }

[[bin]]
name = "catalog"
path = "src/catalog.rs"